[Greeter]
background=/usr/share/backgrounds/arcanus/arcanus-login-wallpaper.png
logo=/usr/share/pixmaps/arcanus-logo.png
theme-name=Arcanus-Dark
icon-theme-name=Mint-Y
draw-grid=false
show-hostname=false
only-on-monitor=primary
